return {
  READ_FAILED = 10,
  ADDRESS_NULL = 20,
  ADDRESS_OVERFLOW = 21,
  CIRCULAR_LIST_TOO_LONG = 30,
  STRING_TOO_LONG = 40,
  VECTOR_INVALID_RANGE = 50,
  VECTOR_MISALIGNED = 51,
  VECTOR_TOO_LONG = 52,
}
