local T = require("mempeep.T")
local i32 = T.i32()
assert(i32["kind"] == "i32")
local arr = T.array(i32, 5)
T.validate(arr)
assert(arr["kind"] == "array")
assert(arr["type_ref"] == i32)
assert(arr["count"] == 5)
local stru = T.struct("Item")
T.validate(stru)
assert(stru["kind"] == "struct")
assert(stru["name"] == "Item")
local circ = T.circular_list(stru)
T.validate(circ)
assert(circ["kind"] == "circular_list")
assert(circ["type_ref"] == stru)
local opt_ref = T.optional_ref(i32)
T.validate(opt_ref)
assert(opt_ref["kind"] == "ptr")
assert(opt_ref["type_ref"] == i32)
local vec = T.vector(i32)
T.validate(vec)
assert(vec["kind"] == "vector")
assert(vec["type_ref"] == i32)

